micronaut:
  application:
    name: vehicle-status
  http:
    services:
      insurance:
        url: http://localhost:8081
#        url: http://insurance.com
      maintenance-frequency:
        url: http://localhost:8081
#        url: http://topgarage.com
vahicle-status:
  vin: "4Y1SL65848Z411439"
